# -*- coding: utf-8 -*-
"""LINEbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dzTfjh6Rhwl5CrcG-Nz-QqtiD-f-_gsQ
"""

import json
from linebot import LineBotApi
from linebot.models import TextSendMessage
from re import TEMPLATE

file = open('info.json', 'r')
info = json.load(file)

CHANNEL_ACCESS_TOKEN = info['CHANNEL_ACCESS_TOKEN']
line_bot_api = LineBotApi(CHANNEL_ACCESS_TOKEN)

def main():
  USER_ID = info['USER_ID']
  messages = TextSendMessage(text="おはよう\nテストコメントだよ")
  line_bot_api.push_message(USER_ID, messages=messages)

if __name__ =="__main__":
  main()